package proyectopoo;

import javax.swing.*;

/**
 * @author franjo2001
 */
public class Venta extends JFrame {

    // variables locales que se usan como auxiliares y controladoras
    boolean b = false;
    private double subtotal = 0;
    // objeto que se usa como auxiliar
    VentaProducto pAux = new VentaProducto();

    /**
     * Creates new form Venta
     */
    // configuracion de la ventana
    public Venta() {
        initComponents();
        setTitle("Dino Store/Ventas");// titulo de la ventana
        setLocationRelativeTo(null);// se establece la ubicacion de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JButton();
        labelNombreProdc = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btCantidad = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtGetCantidad = new javax.swing.JLabel();
        txtGetNombre = new javax.swing.JLabel();
        txtGetSubtotal = new javax.swing.JLabel();
        txtGetIva = new javax.swing.JLabel();
        txtGetTotal = new javax.swing.JLabel();
        txtMensaje1 = new javax.swing.JLabel();
        txtMensaje2 = new javax.swing.JLabel();
        txtGetPrecioUni = new javax.swing.JLabel();
        txtMensaje3 = new javax.swing.JLabel();
        txtGetPrecio = new javax.swing.JLabel();
        txtMensaje4 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Punto de Venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese nombre o inicial del producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 442, 31));

        txtBuscar.setText("Buscar");
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, 31));

        labelNombreProdc.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreProdc.setText("Nombre Producto:");
        getContentPane().add(labelNombreProdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));

        labelStock.setForeground(new java.awt.Color(255, 255, 255));
        labelStock.setText("Stock");
        getContentPane().add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 174, -1, -1));

        labelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        labelPrecio.setText("Precio");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 174, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 206, 171, 30));

        lblStock.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 206, 70, 30));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 206, 50, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("$");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 206, 16, 30));

        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 497, -1, -1));

        btCantidad.setText("Agregar al carrito");
        btCantidad.setName("comprar"); // NOI18N
        btCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(btCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 281, -1, -1));

        btnGenerar.setText("Generar Pago");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 497, -1, -1));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 278, 51, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese la cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 284, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 315, 360, 30));

        txtGetCantidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetCantidad.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 387, 136, 39));

        txtGetNombre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 387, 136, 39));

        txtGetSubtotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 351, 171, 30));

        txtGetIva.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetIva.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 413, 171, 30));

        txtGetTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetTotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 461, 171, 30));

        txtMensaje1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMensaje1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 351, 171, 30));

        txtMensaje2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMensaje2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 351, 80, 30));

        txtGetPrecioUni.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetPrecioUni.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetPrecioUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 387, 136, 39));

        txtMensaje3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMensaje3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMensaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 351, 110, 30));

        txtGetPrecio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtGetPrecio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtGetPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 389, 136, 37));

        txtMensaje4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtMensaje4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMensaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 351, 125, 30));

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 539, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    // busqueda de lo ingresado
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        //variables
        String nombre_buscar = txtBusqueda.getText();
        // asignaciopn de los espacios que se presentaran si no existe el dato
        lblNombre.setText("No existe el producto");
        lblStock.setText("-----");
        lblPrecio.setText("------");
        b = false;
        for (Producto p : Registro.productos) {
            //Verificamos el nombre a buscar este contenido 
            if (p.getNombre().contains(nombre_buscar.toLowerCase())) {
                b = true;
                lblNombre.setText(p.getNombre());
                lblStock.setText(String.valueOf(p.getCantidad()));
                lblPrecio.setText(String.valueOf(p.getPrecio()));
                // guardado del nombre y precio en otro objeto para usarlo despues
                pAux.setNombre(p.getNombre());
                pAux.setPrecio(p.getPrecio());
                pAux.setCantidad(p.getCantidad());
            }
        }
    }//GEN-LAST:event_txtBuscarActionPerformed
    // boton menu el cual vuelve al menu
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu objmenu = new Menu();
        objmenu.show();
        // cerrar la ventana
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // boton que registra la cantidad
    private void btCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCantidadActionPerformed
        // TODO add your handling code here:
        // el boton funcionara solo si existe el producto
        if (b) {
            // lectura del dato
            int cantidad = Integer.parseInt(txtcantidad.getText());
            // validacion si se puede comprar esa cantidad
            if (cantidad <= pAux.getCantidad()) {
                // almacenamos en el objeto la cantidad
                pAux.setCantidad(cantidad);
                // calculamos el subtotal
                pAux.calcularSubtotal();
                // sumamos el subtotal para la presentacion final
                subtotal += pAux.getSubtotal();
                // visualizacion previa de los datos
                txtMensaje1.setText("Nombre del producto");
                txtMensaje2.setText("Cantidad");
                txtMensaje3.setText("Precio unitario");
                txtMensaje4.setText("Precio sin iva");
                txtGetNombre.setText(pAux.getNombre());
                txtGetCantidad.setText(String.valueOf(cantidad));
                txtGetPrecioUni.setText(String.valueOf("$" + pAux.getPrecio()));
                txtGetPrecio.setText(String.valueOf("$" + pAux.getSubtotal()));

                // en caso de poderse se presentara..
                lblCantidad.setText("Agregado");
                // limpieza de las casillas
                clearList();
            } else {
                // si no existe se presentara...
                lblCantidad.setText("Verifique el Stock");
                // limpieza de la casilla de cantidad
                txtcantidad.setText("");
            }
        }
    }//GEN-LAST:event_btCantidadActionPerformed
// generar los valores finales
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // almacenamiento del subtotal
        pAux.setSubtotal(subtotal);
        // calculo del iva
        pAux.calcularIva();
        // calculo del total
        pAux.calcularTotal();
        // presentacion de los valores obtenidos
        txtGetSubtotal.setText("Subtotal: $" + pAux.getSubtotal());
        txtGetIva.setText("Iva: $" + pAux.getIva());
        txtGetTotal.setText("Total: $" + pAux.getTotal());
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    public void clearList() {
        // coloca los valores ingresados en espoacios vacios
        txtBusqueda.setText("");
        txtcantidad.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCantidad;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelNombreProdc;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JButton txtBuscar;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel txtGetCantidad;
    private javax.swing.JLabel txtGetIva;
    private javax.swing.JLabel txtGetNombre;
    private javax.swing.JLabel txtGetPrecio;
    private javax.swing.JLabel txtGetPrecioUni;
    private javax.swing.JLabel txtGetSubtotal;
    private javax.swing.JLabel txtGetTotal;
    private javax.swing.JLabel txtMensaje1;
    private javax.swing.JLabel txtMensaje2;
    private javax.swing.JLabel txtMensaje3;
    private javax.swing.JLabel txtMensaje4;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables

}
